[profile.default]
out = 'foundry-out'
solc_version = '0.8.26'
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "cancun"
gas_limit = "3000000000"
fuzz_runs = 10_000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100

[profile.ci]
fuzz_runs = 100_000

[profile.gas]
gas_limit=30_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
unichain_sepolia = "https://sepolia.unichain.org"
base_sepolia = "https://sepolia.base.org"
op_sepolia = "https://sepolia.optimism.io"

